#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '^.*/cmd/.*\.go$'; then
        echo "! You need to regenerate the CLI docs!"
    fi
done