#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0

checkSetX() {
    LINES=$(grep -rnHE "(set.*[-+]x)" "$FILE")

    if [ -n "$LINES" ]; then
        echo "! Found \`set -x\`: $LINES"
        SUCCESS=1
    fi
}

if [ -n "$GITHOOKS_ON_DEMAND_EXEC" ]; then
    STAGED_FILES=$(find . -name '*.sh')
fi

for FILE in $STAGED_FILES; do
    echo "$FILE" | grep -qE '\.sh$' && checkSetX "$FILE"
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No \`set -x\` found"
else
    exit "$SUCCESS"
fi