#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0

checkTodo() {
    LINES=$(grep -rnHE "(TODO|FIXME)" "$1")

    if [ -n "$LINES" ]; then
        echo "! TODO or FIXME found in: $LINES"
        SUCCESS=1
    fi
}

for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qvE '(/cover/|/pre-commit/no-todo-or-fixme|\.go|\.md)'; then
        checkTodo "$FILE"
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No TODO or FIXME detected"
else
    exit "$SUCCESS"
fi
