#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0

checkTab() {
    LINES=$(grep -rnH "$(printf '\t')" "$1")

    if [ -n "$LINES" ]; then
        echo "! Tab character found in: $LINES"
        SUCCESS=1
    fi
}

if [ -n "$GITHOOKS_ON_DEMAND_EXEC" ]; then
    STAGED_FILES=$(find . -name '*.sh')
fi

for FILE in $STAGED_FILES; do
    checkTab "$FILE"
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No tab characters detected"
else
    exit "$SUCCESS"
fi
