#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0
if [ -n "$GITHOOKS_ON_DEMAND_EXEC" ]; then
    STAGED_FILES=$(find . -name '*.sh')
elif [ -n "${STAGED_FILES_REFERENCE}" ]; then
    STAGED_FILES="$(cat "${STAGED_FILES_REFERENCE}")"
fi

for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '\.sh$' &&
        echo "$FILE" | grep -qv '/cover/' &&
        grep -nrHE 'shellcheck.*disable' "$FILE" | grep -v '# shellcheck disable=SC'; then
        echo "! Wrong shellcheck ignored format: use \`# shellcheck disable=SCnnnn\` in $FILE"
        SUCCESS=1
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No shellcheck ignore format issues found"
else
    exit 1
fi
