#!/bin/sh
DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

if ! shellcheck --version >/dev/null 2>&1; then
    echo "_ Skipping shellcheck - not installed"
    exit 0
fi

SUCCESS=0
if [ -n "$GITHOOKS_ON_DEMAND_EXEC" ]; then
    STAGED_FILES=$(find . -name '*.sh')
fi

for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '\.sh$' &&
        ! shellcheck "$FILE"; then
        echo "! shellcheck problems detected in: $FILE"
        SUCCESS=1
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* shellcheck OK"
else
    exit "$SUCCESS"
fi
