#!/bin/sh

if ! shellcheck --version >/dev/null 2>&1; then
    echo "_ Skipping shellcheck - not installed"
    exit 0
fi

if shellcheck ./*.sh ./tests/*.sh .githooks/*/*; then
    echo "* shellcheck OK"
else
    echo "! shellcheck problems detected"
    exit 1
fi
