#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
. "$DIR/.export-staged"

assertStaged

SUCCESS=0
for FILE in $STAGED_FILES; do
    if echo "$FILE" | grep -qE '\.sh$' &&
        echo "$FILE" | grep -qv '/cover/' &&
        grep -nrHE 'shellcheck.*disable' "$FILE" | grep -vE '# shellcheck disable=SC[0-9]+(,SC[0-9]+)*'; then
        echo "! Wrong shellcheck ignored format: use \`# shellcheck disable=SCnnnn\` in $FILE"
        SUCCESS=1
    fi
done

if [ "$SUCCESS" = "0" ]; then
    echo "* No shellcheck ignore format issues found"
else
    exit 1
fi
