#!/bin/sh
CHANGES="$(git diff --name-only origin/master..HEAD base-template.sh install.sh)"
if [ -z "$CHANGES" ]; then
    # stop here if there are changes for this push
    exit 0
fi

VERSION_DATE=$(date +%y%m.%d%H%M)
VERSION_COMMIT=$(git rev-parse --short=6 HEAD)

echo "* Setting version number to: ${VERSION_DATE}-${VERSION_COMMIT}"

# update the version number
for FILENAME in base-template.sh install.sh; do
    sed "s/^# Version: .*/# Version: ${VERSION_DATE}-${VERSION_COMMIT}/" "$FILENAME" >"${FILENAME}.copy"
    mv "${FILENAME}.copy" "$FILENAME"
done

# restore the execute flag on the install script
chmod +x install.sh

# rewrite the last commit to include the version number change
git add base-template.sh install.sh
git commit --amend --no-edit --no-verify >/dev/null
