#!/bin/sh
# Pre-commit hook to test for a properly working Git LFS.

lfs_config_check_failed() {
    if [ -n "$1" ]; then
        echo "$1" >&2
    else
        echo "! Git LFS filter are not installed properly!" >&2
        echo "  Run: \`git lfs install\` to correct this." >&2
    fi

    exit 1
}

command -v git-lfs >/dev/null 2>&1 ||
    lfs_config_check_failed "This repository needs Git LFS but \`git-lfs\` was not found on your path."

[ "$(git config --get filter.lfs.required)" = "true" ] || lfs_config_check_failed
git config --get filter.lfs.clean | grep -q "git-lfs" || lfs_config_check_failed
git config --get filter.lfs.smudge | grep -q "git-lfs" || lfs_config_check_failed
git config --get filter.lfs.process | grep -q "git-lfs" || lfs_config_check_failed
